spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/THyyy/config-repo.git
          username: THyyy
          password: woainiCL520
#          basedir: /tmp/spring-cloud-repo
          basedir: D:\Gitlibrary\config-repo\springcloud-sell
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"